# Generated by Django 4.0.5 on 2022-07-02 03:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
